### ISSUE TITLE
Нет прокрутки в разделе серверов

### ISSUE THREAD

**Issue by theRamanovich** [sirekanian/outline#3]
Здравствуйте.
Есть проблем:
1. Если какой-то сервер был добавлен, то удалить его нет возможности из приложения, что не удобно, так как сервера иногда меняются.
2. Если у меня большое количество серверов, то видно только некоторое количество, остальные просто невозможно открыть и просмотреть. Сделайте пожалуйста прокрутку в разделе серверов. 
![Screenshot_20231025_140331_org sirekanyan outline](https://github.com/sirekanian/outline/assets/148968969/152b2e31-eb8a-4e99-97d3-5a57b51d40dc)

**Comment by theRamanovich** [comment]
Супер. Скачал новую версию - все работает. Вы лучший!!!

**Comment by sirekanian** [comment]
v0.1.13 
- Added vertical scroll for drawer 65d1ad7e5e4d9f69a8828a231d823b89fc6a1e71
- Added delete server button 3abcbd72ade07465872839cc7e08c64b18a4366a

v0.1.13
- Добавлен вертикальный скролл для списка серверов 65d1ad7e5e4d9f69a8828a231d823b89fc6a1e71
- Добавлена возможность удаления сервера 3abcbd72ade07465872839cc7e08c64b18a4366a

Изменения уже доступны в beta-версии приложения на Google Play, через некоторое время обновление появится в Google Play для всех пользователей, а также в маркете FDroid.

Буду рад обратной связи, заводите еще тикеты!
