### ISSUE TITLE
Сортировка

### ISSUE THREAD

**Issue by theRamanovich** [sirekanian/outline#4]
Ещё возникла одна просьба.
Можно ли в будущем сделать настройку сортировки ключей/серверов по алфавиту?
А то сейчас не удобно, что все в разброс. Особенно когда на сервере по 40 ключей и 16 серверов.
Заранее благодарю.

**Comment by theRamanovich** [comment]
Все думал, что забыл написать и вот вспомнил, когда вы уже выпустили релиз.
В следующем обновлении можете еще добавить отображение количества ключей на сервере?
Сейчас нет этого и приходится считать, чтобы не добавить лишнего человека на сервер, так как есть лимиты.
А при отображении количества ключей, можно ускорить поиск нужного сервера в разы. 
Хочется по максимум заменить настольное (на ноутбуке) приложение и спокойно находится только с планшетом вдали от дома (ноутбука)

**Comment by theRamanovich** [comment]
Выже не пропустите сообщение? :) или нужно новую задачку лучше завести?

**Comment by sirekanian** [comment]
Спасибо за ваше терпение и ожидание :)

1. Сортировка ключей уже доступна с версии v0.1.15. Сейчас ключи можно сортировать по:

    - id ключа
    - имени ключа (от А до Я)
    - трафику (от большего к меньшему)

    В будущих релизах, возможно, добавлю сортировку в обратном порядке, если будет такая потребность.

    @theRamanovich А как вы считаете, нужна ли сортировка в обратном порядке?

2. Что касается количества ключей и сортировки серверов, см. тикет #6.

**Comment by theRamanovich** [comment]
@sirekanian пока нет необходимости обратного порядка сортировки. Все остальное для наилучшей/продуктивной работы реализовано. Спасибо огромное за ваш труд 🙏
