### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [sirekanian/outline#5]
ref: https://monitor.f-droid.org/builds/log/org.sirekanyan.outline/18#site-footer

Building locally to get the diff brb

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/45099f62eb12f191434cfc4434191c433c930f19

**Comment by licaon-kter** [comment]
difflog: [out18.log](https://github.com/sirekanian/outline/files/13333734/out18.log)

local APK: [org.sirekanyan.outline_18.apk.ZIP](https://github.com/sirekanian/outline/files/13333737/org.sirekanyan.outline_18.apk.ZIP)_(remove .ZIP)_


fyi @linsui

**Comment by linsui** [comment]
@licaon-kter Newer versions has been built.
