### ISSUE TITLE
Отображение кол-ва ключей

### ISSUE THREAD

**Issue by theRamanovich** [sirekanian/outline#6]
Простите, если лишний раз завожу "тикет", но может прошлый доп.коммент не отображается.
1. Добавьте, пожалуйста, отображение кол-ва ключей на сервере. Будет очень удобно отслеживать и распределять людей при новых подключениях. Пример на фото во вложении.
2. После обновления перемешались сервера и теперь они не по порядку 🫠 а хочется удобства и чтобы они были отсортированы по алфавиту. Текущее отображение, также есть на фото во вложении. ![image](https://github.com/sirekanian/outline/assets/148968969/64a5d12e-c6ae-4731-998a-b7193b74ba78)![image](https://github.com/sirekanian/outline/assets/148968969/14ace34b-70f3-474f-b294-1591058124a0)

**Comment by sirekanian** [comment]
Спасибо, что завели новый тикет! Я занимаюсь этим приложением в свободное время и могу долго реализовывать новые фичи :)

1. Количество ключей уже можно посмотреть в новом релизе [v0.1.23](https://github.com/sirekanian/outline/releases/tag/v0.1.23), для этого нажмите на эту кнопку:

    ![photo_2024-01-02_23-51-15](https://github.com/sirekanian/outline/assets/104234264/143934b4-3923-4e2f-abc8-00810ab14d95)

2. Сортировка сервером теперь будет по алфавиту (в будущем, возможно, можно будет настраивать порядок сортировки, если будет потребность такой фичи).
